### ISSUE TITLE
Not compatible with react 16

### ISSUE THREAD

**Issue by jadekler** [zilverline/react-tap-event-plugin#109] opened 2017-09-27 14:52 UTC
```
ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventConstants' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 22:21-60
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ ./src/ui/app.js

ERROR in ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-41
 @ ./src/ui/app.js

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginUtils' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 23:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ ./src/ui/app.js

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPropagators' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 24:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ ./src/ui/app.js

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/SyntheticUIEvent' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 25:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ ./src/ui/app.js

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/ViewportMetrics' in '/Users/deklerkj/dev/go/src/github.com/pasa-v2x/cdot-demo-ui/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 27:22-62
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ ./src/ui/app.js
```

**Comment by kachkaev** [comment] 2017-09-27 20:58
Seems like a duplicate of https://github.com/zilverline/react-tap-event-plugin/issues/109 @s0meone could you please have a look? This issue will be really hot in the next few days following the final release of react 16.0 🔥 😄

**Comment by Tasemu** [comment] 2017-09-28 08:24
+1 keen to upgrade but tap-event is breaking. :)

**Comment by s0meone** [comment] 2017-09-28 11:57
I've updated the plugin to version 3.0.0, to be compatible with React 16. I had to copy a big chunk of React internals to keep it working. This solution will probably not last for future versions. React is making it harder and harder to keep this plugin going.

Please test the latest commit in your application and let me know the results so I can publish to npm.

**Closed** 2017-09-28 12:16 UTC
